### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by samypr100** [Birdasaur/Trinity#15]
- [x] Update CI to make Release Artifacts
- [ ] Provide initial Changelog

**Comment by Birdasaur** [comment]
Possibly OBE since we are discussing converting to Calendar format releases.

**Comment by samypr100** [comment]
@Birdasaur yup, updated title and description to fit better

**Comment by Birdasaur** [comment]
@samypr100 what did you have in mind for implementing a changelog? Is it something you want to automate?

**Comment by samypr100** [comment]
I think for first release we want summary of highlights / current features alongside the automatic changelog Github generates for you.

After that I think we can keep using the auto generated changelog github provides as long as the issue titles are descriptive enough.

**Comment by samypr100** [comment]
@Birdasaur 

This is how it looks with the auto gen now. So for the first release we'll have to do some manual input first along side the auto gen. For future releases the autogen will be quite good at capturing differences.

![auto_gen_release_notes](https://github.com/Birdasaur/Trinity/assets/3933065/80f254a8-e40a-4491-90b3-aed9b579e74e)

**Comment by Birdasaur** [comment]
@samypr100  Now that the LitFX dependency has been updated what remains to be done prior to making a tagged release?

**Comment by samypr100** [comment]
@Birdasaur Probably would be nice to have a FXyz update

**Comment by samypr100** [comment]
Finished by https://github.com/Birdasaur/Trinity/releases/tag/v2023.09.30 release
