### ISSUE TITLE
Concave Hull Support

### ISSUE THREAD

**Issue by Birdasaur** [Birdasaur/Trinity#42]
Implement 3D Concave Hull generator that uses Convex Hull (or some other set of points) as input.
Since typically in a non trivial case there will be multiple possible concave hulls derivable from a tolerance variable, make this variable accessible to the user.
Make 3D view that generates a collection of possible Concave Hulls based on a discretization across the tolerance variable.
Let the user select the hull they prefer.
Maybe make it a 3D carousel that rotates for the lulz.

**Comment by Birdasaur** [comment]
@samypr100 
As part of the development done on this branch I've added support for directly ingesting .flac audio files. (previously only .wav was supported) I had to add a new dependency:
`
        <dependency>
          <groupId>org.jflac</groupId>
          <artifactId>jflac-codec</artifactId>
          <version>1.5.2</version>
        </dependency>  
       `
We will need to update the gradle scripts and possibly the YAML for the build actions to match?
We might want to update to the latest versions for the hansolo charts while we are at it but not required.

**Comment by samypr100** [comment]
@Birdasaur Pushed changes to the branch to make it work with gradle and native jpms

**Comment by samypr100** [comment]
RE: hansolo, we'll have to support JDK 21 before updating. JDK 21 doesn't work yet with native build.

**Comment by Birdasaur** [comment]
pulled your build updates. Verified that maven build configurations still work locally. Moved local dev to JDK 21.0.1 etc.

**Comment by samypr100** [comment]
Can you open a draft PR to see if CI fails?

**Comment by Birdasaur** [comment]
In the pipe 5x5.

**Comment by Birdasaur** [comment]
Looks like the Gradle JLink and JPackage builds failed across the OS list.

**Comment by Birdasaur** [comment]
Clue:
![image](https://github.com/Birdasaur/Trinity/assets/4649925/17c2b4ea-965e-4253-becb-7b6ab421c0af)

**Comment by samypr100** [comment]
Seems this is the error
> Error: Module jflac.codec does not read a module that exports javax.sound.sampled.spi

**Comment by samypr100** [comment]
Likely JDk21 related being more strict, I think we can fix

**Comment by Birdasaur** [comment]
According to the manifest jflac was compiled using a recent (ish) version of JDK 8.

**Comment by samypr100** [comment]
I pushed an update, let me know if it helps
